Repository adina-hc/pata-de-perro, pull requests merged in 2021-08, with the labels that each got.

#34 Modified model to Activity
  server/models/Activity.js
  server/models/index.js
Labels: enhancement, step 1

#35 Feature/#4
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement, step 1

#36 feature/#15
  client/src/utils/GlobalState.js
Labels: enhancement, step 1

#37 feature/#14
  client/src/utils/actions.js
Labels: enhancement, step 1

#44 created activity list component and function
  client/src/components/ActivityList/index.js
  client/src/components/ProductList/index.js
Labels: enhancement, step 1

#49 feature/Changes-App-Run
  client/src/components/Cart/index.js
  client/src/pages/Contact.js
  client/src/pages/Detail.js
  client/src/pages/Home.js
Labels: enhancement, step 1

#51 Fixed some issues with graphl
  client/src/App.js
  client/src/components/ActivityList/index.js
  client/src/utils/helpers.js
  server/config/seeds.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement, step 1

#54 Added waves to the App
  client/src/App.js
  client/src/pages/Home.js
Labels: enhancement, step 1

#56 added activities with their respective images
  server/config/seeds.js
Labels: enhancement

#57 success page act victor 160821
  client/src/pages/Success.js
Labels: enhancement

#58 Feature/#9 profile page
  client/src/App.js
  client/src/components/ProfileTemplate/index.js
  client/src/components/elements/Wave.js
  client/src/pages/Home.js
  client/src/pages/Profile.js
Labels: enhancement

#59 Feature/cart components and activities
  client/package-lock.json
  client/package.json
  client/public/images/adventure1.png
  client/public/images/adventure2.png
  client/public/images/adventure3.png
  client/public/images/adventure4.png
  client/public/images/beach1.png
  client/public/images/beach2.png
  client/public/images/beach3.png
  client/public/images/beach4.png
  client/public/images/spa1.png
  client/public/images/spa2.png
  client/public/images/spa3.png
  client/public/images/spa4.png
  client/public/index.html
  client/src/App.js
  client/src/components/ActivityItem/Card.js
  client/src/components/ActivityItem/index.js
  client/src/components/ActivityList/index.js
  client/src/components/Cart/index.js
  client/src/components/Cart/style.css
  client/src/components/CartItem/index.js
  client/src/components/Header/Header.js
  client/src/components/Header/IconTravel.js
  client/src/components/Header/Title.js
  client/src/components/elements/Container.js
  client/src/components/elements/Plane.js
  client/src/components/elements/Wave.js
  client/src/pages/Activities.js
  client/src/pages/Detail.js
  client/src/pages/Home.js
  design/beach.html
  package-lock.json
  package.json
  server/config/seeds.js
Labels: enhancement

#61 feature/CartCategories
  client/src/components/ActivityItem/Card.js
  client/src/components/ActivityItem/index.js
  client/src/components/ActivityList/index.js
  client/src/components/CategoryMenu/index.js
Labels: enhancement

#64 Feature/Design changes and some bug fix
  client/src/components/ActivityItem/index.js
  client/src/components/ActivityList/index.js
  client/src/components/Cart/index.js
  client/src/components/LoginForm/index.js
  client/src/components/Nav/index.js
  client/src/components/ProfileTemplate/index.js
  client/src/components/SingupForm/index.js
  client/src/components/elements/CardDetails.js
  client/src/components/elements/Container.js
  client/src/components/elements/Wave.js
  client/src/pages/Aboutus.js
  client/src/pages/Activities.js
  client/src/pages/ContactUs.js
  client/src/pages/Detail.js
  client/src/pages/Login.js
  client/src/pages/Profile.js
  client/src/pages/Signup.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/utils/auth.js
Labels: enhancement

#66 Added new stripe account key
  client/src/components/CategoryMenu/index.js
  client/src/components/Nav/index.js
  server/models/Activity.js
  server/schemas/resolvers.js
Labels: enhancement

#67 Fixed the issue with stripe
  server/models/Activity.js
  server/schemas/resolvers.js
Labels: enhancement

#71 Contact us
  client/src/components/LoginForm/index.js
  client/src/pages/ContactUs.js
  client/src/utils/styles.css
Labels: enhancement

#73 Fixing contact-us
  client/src/pages/ContactUs.js
Labels: enhancement

#75 Feature/code prepare heroku
  client/package.json
  client/public/index.html
  client/src/components/Cart/index.js
  client/src/pages/Aboutus.js
  client/src/pages/ContactUs.js
  package.json
Labels: enhancement

#79 Feature/fixed serviceworker
  client/public/service-worker.js
  client/src/index.js
  client/src/serviceWorker.js
  server/server.js
Labels: bug
